language: node_js
node_js:
  - "10.8.0"
install:
  - npm i
  - npm i --prefix demo
script:
  - npm run travis
  - npm run lint --prefix demo
cache:
  directories:
    - node_modules
    - demo/node_modules
sudo: false
